# Configuraçoes do app
app:
  contextPath: '@project.artifactId@'
  version: '@project.version@'
  description: '@project.description@'
  organization: '@project.organization.name@'
  name: '@project.name@'

#Configurações do Spring
spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        temp.use_jdbc_metadata_default: 'false'
        event.merge.entity_copy_observer": 'allow'
    database-platform: 'org.hibernate.dialect.PostgreSQL95Dialect'
  jackson:
    time-zone: America/Sao_Paulo
    serialization:
      write-dates-as-timestamps: 'false'
    deserialization:
      fail-on-unknown-properties: 'true'
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    format:
      time: HH:mm:ss
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

#Configurações do servidor
server:
  servlet:
    context-path: /@project.artifactId@
  error:
    include-stacktrace: never
  port: '8086'

#Configurações do Swagger
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha


