#Configuração de datasource
spring:
  datasource:
    username: web_service
    url: jdbc:postgresql://localhost:5432/db_home_ponto
    password: post#2022
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'

# API GERA LOG
api:
  log:
    geraLog: http://192.168.200.70:9065/gera-log-api/log
    geraLogId: http://192.168.200.70:9065/gera-log-api/log/gerar-id

#Configuração de log
logging:
  level:
    br:
      com:
        automatodev: DEBUG
        zaxxer:
         hikari:
            HikariConfig: DEBUG
    org:
      hibernate:
        engine:
          jdbc: OFF
        SQL: OFF
        jpa: OFF
        event: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF
      springframework:
        web: 
          HttpLogging: OFF
          nodeValue: OFF  
          client:
            RestTemplate: OFF